const CREATE_LIST = "CREATE_LIST"
const DELETE_LIST = "DELETE_LIST"
const CHANGE_LIST_TITLE = "CHANGE_LIST_TITLE"
const ADD_TODO_TO_LIST = "ADD_TODO_TO_LIST"

export { CREATE_LIST, DELETE_LIST, CHANGE_LIST_TITLE, ADD_TODO_TO_LIST }