const TOGGLE_CREATING_LIST = "TOGGLE_CREATING_LIST"
const TOGGLE_RENAMING_LIST = "TOGGLE_RENAMING_LIST"
const TOGGLE_DELETING_LIST = "TOGGLE_DELETING_LIST"
const TOGGLE_CREATING_TODO = "TOGGLE_CREATING_TODO"
const TOGGLE_SHOWING_COMPLETED = "TOGGLE_SHOWING_COMPLETED"
const TOGGLE_SHOWING_IMPORTANT = "TOGGLE_SHOWING_IMPORTANT"
const SET_ACTIVE_LIST_ID = "SET_ACTIVE_LIST_ID"
const SET_SEARCH_QUERY = "SET_SEARCH_QUERY"

export {
  TOGGLE_CREATING_LIST,
  TOGGLE_RENAMING_LIST,
  TOGGLE_DELETING_LIST,
  TOGGLE_CREATING_TODO,
  TOGGLE_SHOWING_COMPLETED,
  TOGGLE_SHOWING_IMPORTANT,
  SET_ACTIVE_LIST_ID,
  SET_SEARCH_QUERY
}