const SET_ACTIVE_TASK_ID = "SET_ACTIVE_TASK_ID"
const TOGGLE_TODO_TITLE_CHANGING = "TOGGLE_TODO_TITLE_CHANGING"
const TOGGLE_DUE_DATE_CHANGING = "TOGGLE_DUE_DATE_CHANGING"
const TOGGLE_TODO_NOTE_CHANGING = "TOGGLE_TODO_NOTE_CHANGING"
const TOGGLE_TODO_DELETING_CONFIRMATION = "TOGGLE_TODO_DELETING_CONFIRMATION"

export {
  SET_ACTIVE_TASK_ID,
  TOGGLE_TODO_TITLE_CHANGING,
  TOGGLE_DUE_DATE_CHANGING,
  TOGGLE_TODO_NOTE_CHANGING,
  TOGGLE_TODO_DELETING_CONFIRMATION
}