const CHANGE_TODO_TITLE = "CHANGE_TODO_TITLE"
const CHANGE_TODO_NOTE = "CHANGE_TODO_NOTE"
const CHANGE_DUE_DATE = "CHANGE_DUE_DATE"
const SET_COMPLETED = "SET_COMPLETED"
const SET_IMPORTANT = "SET_IMPORTANT"
const DELETE_TODO = "DELETE_TODO"

export { CHANGE_TODO_TITLE, CHANGE_TODO_NOTE, CHANGE_DUE_DATE, SET_COMPLETED, SET_IMPORTANT, DELETE_TODO }