const TOGGLE_TODO_TITLE_CHANGING = "TOGGLE_TODO_TITLE_CHANGING"
const TOGGLE_DUE_DATE_CHANGING = "TOGGLE_DUE_DATE_CHANGING"
const TOGGLE_TODO_DELETING_CONFIRMATION = "TOGGLE_TODO_DELETING_CONFIRMATION"

export {
  TOGGLE_TODO_TITLE_CHANGING,
  TOGGLE_DUE_DATE_CHANGING,
  TOGGLE_TODO_DELETING_CONFIRMATION
}