const TOGGLE_SHOWING_USER_PANEL = "TOGGLE_SHOWING_USER_PANEL"
const TOGGLE_IS_LOGOUTING = "TOGGLE_IS_LOGOUTING"
const SAVE_SETTINGS = "SAVE_SETTINGS"

export { TOGGLE_SHOWING_USER_PANEL, TOGGLE_IS_LOGOUTING, SAVE_SETTINGS }