export const CREATE = "Create"
export const RENAME = "Rename"
export const DELETE_LIST = "Delete"
export const ADD = "Add"
export const DELETE_TASK = "Delete"
export const SAVE_SETTINGS = "Save"
export const IS_LOGOUTING = "Sign Out"
export const SAVE_CUSTOM_DUE_DATE = "OK"